export { default as Navbar } from './Navbar/Navbar'
export { default as Footer } from './Footer/Footer'
export { default as InfoSection } from './InfoSection/InfoSection'
export { default as LogIn } from './LogIn/LogIn'
export { default as SignUp } from './SignUp/SignUp'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as AddCocktailPage } from './AddCocktailPage/AddCocktailPage'
export { default as BrowseAvailableCocktails } from './BrowseAvailableCocktails/BrowseAvailableCocktails'
export { default as IngredientForm } from './IngredientForm/IngredientForm'
export { default as IngredientList } from './IngredientList/IngredientList'
export { default as EditIngredientPage } from './EditIngredientPage/EditIngredientPage'
export { default as IngredientListFilters } from './IngredientListFilters/IngredientListFilters'
// this is to neatly export all the nested files that are in the components folder.